# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
